### ISSUE TITLE
优化多次基本没什么变化

### ISSUE THREAD

**Issue by SlamSmallFish** [hku-mars/HBA#14]
您好，请问我运行多次hba.launch，但是优化出来的结果几乎没什么变化，无法回到同一地方，无法像您在github上展示的kitti00那样最后回到起点，可以提供一些建议吗？
![screenshot-20230720-184402](https://github.com/hku-mars/HBA/assets/126395838/2eee6935-1e79-4eac-85ff-8229ada92626)
![screenshot-20230720-194632](https://github.com/hku-mars/HBA/assets/126395838/743ec04f-b767-410a-a841-784e6bcffae1)

**Comment by JACKLiuDay** [comment]
> @SlamSmallFish 你好，我的建议是先做一个回环检测+位姿图优化，再用hba优化剩余分层。你的这个场景只有首尾这里有匹配关系，如果voxel_size不够大，没有把图二分层的地面放到一个voxel内，其实位姿就没有被优化。

Hi, I tried something new on my campus with HBA. This environment only has a closed loop at the beginning and end. And the STD project works not so well. Do you have some advice.  How to form an effective closed loop for an environment that only has a closed loop at the beginning and the end?  Moreover, this environment is still a large symmetrical circle, and many closed-loop detections have failed.  https://github.com/hku-mars/STD/issues/22

**Comment by samsdolphin** [comment]
Hi @JACKLiuDay, we have encountered this issue before. My suggestion is to manually select the keyframe and perform the ICP or whatever to determine the relative transformation and add it to the pgo.

**Comment by JACKLiuDay** [comment]
> Hi @JACKLiuDay, we have encountered this issue before. My suggestion is to manually select the keyframe and perform the ICP or whatever to determine the relative transformation and add it to the pgo.

Hi, thank you for your advice. I will try it.

**Comment by samsdolphin** [comment]
@SlamSmallFish any updates on this issue?
