### ISSUE TITLE
PointClouds are not visualized properly

### ISSUE THREAD

**Issue by pauldeee** [hku-mars/HBA#15]
When using poses from the GTSAM graph with LIO-SAM the point clouds are not aligned properly.

Any ideas how to fix this?

Thanks

**Comment by samsdolphin** [comment]
Hi @pauldeee, I think this is the LIO-SAM issue. There is some extrinsic between the LiDAR and the imu in the LIO-SAM configuration. Please make sure you have the point cloud and the corresponding poses in the same frame, i.e., both in the LiDAR body frame or the imu frame.

**Comment by pauldeee** [comment]
Hi @samsdolphin,

I figured it out. The documentation states the pose file should have the format `tx ty tz qw qx qy qz`.

![image](https://github.com/hku-mars/HBA/assets/52274662/a8e82bae-9a76-416d-9855-d0004e84edee)

When I switch my file to have the poses in the format `tx ty tz qx qy qz qw` it works.

Thanks!

**Comment by pauldeee** [comment]
Sorry, I may have spoken too soon.

It seems while the change I made allows the `visualize.launch` to work correctly `hba.launch` does not produce the expected results...

**Comment by pauldeee** [comment]
Hi @samsdolphin,

Here is a link to some test data: https://drive.google.com/drive/folders/1tn7ZFGnVPS39j8jd3yWux9ykgKQkKUXV?usp=sharing

This works fine with the `visualize.launch`. Could it be a TF issue that's causing it not to work with the `hba.launch` even though it works fine with the `visualize.launch`?

Thanks!

**Comment by samsdolphin** [comment]
Hi @pauldeee, I checked your data and I found only 97 poses (pcds). If this is your total number of point clouds, I would suggest you use the [BALM](https://github.com/hku-mars/BALM) directly as HBA is designed to handle large-scale point cloud mapping, e.g, 1K or 10K or more poses.

**Comment by lvpengxiang** [comment]
I also encountered the same problem as you. Could you please tell me how you modified the code of liosam?
