### ISSUE TITLE
关于重合度较少的大场景性能

### ISSUE THREAD

**Issue by zhh2005757** [hku-mars/HBA#17]
作者您好，想问下对于远距离车辆行驶下的大场景但轨迹重复部分较少（比如只有起终点）的建图优化，HBA能起到多大的作用呢？

**Comment by samsdolphin** [comment]
hba主要是解决pgo回环后的分层问题，如果你的场景只有首尾有重合，pgo之后没有分层，那hba基本上没啥用。

**Comment by zhh2005757** [comment]
> hba主要是解决pgo回环后的分层问题，如果你的场景只有首尾有重合，pgo之后没有分层，那hba基本上没啥用。

好的，感兴您及时的回复！
