### ISSUE TITLE
HBA无法优化

### ISSUE THREAD

**Issue by seanXMU** [hku-mars/HBA#18]
![image](https://github.com/hku-mars/HBA/assets/96283443/6daec483-47cb-46d9-84c8-203140154f63)
使用visualize.launch能正常显示点云，但是优化会直接崩溃退出。请问是什么问题呢？

**Comment by seanXMU** [comment]
发现是ba.hpp 的615行 remove_outlier函数中
`    double threshold = residuals[std::floor((1-ratio)*voxhess.plvec_voxels.size())-1];`
residuals会变成residuals[-1]导致段错误，系统崩溃。请问有什么解决方法吗

**Comment by gongjun136** [comment]
> 发现是ba.hpp 的615行 remove_outlier函数中 ` double threshold = residuals[std::floor((1-ratio)*voxhess.plvec_voxels.size())-1];` residuals会变成residuals[-1]导致段错误，系统崩溃。请问有什么解决方法吗

我也碰到了这种错误，感觉得自己修改下代码

**Comment by zezeuser** [comment]
我也遇到了这个问题，请问是否有解决的方法

> 发现是ba.hpp 的615行 remove_outlier函数中 ` double threshold = residuals[std::floor((1-ratio)*voxhess.plvec_voxels.size())-1];` residuals会变成residuals[-1]导致段错误，系统崩溃。请问有什么解决方法吗

**Comment by samsdolphin** [comment]
@seanXMU @gongjun136 @zezeuser 如果是这个原因，说明整个场景没有检测到平面，`plvec_voxels.size()=0`。我的建议是voxel_size、eigen_ratio都调大一点（如果现在很小的话），如果是使用默认参数还有这个问题。可以把点云截图放上来看看，让我判断一下hba无法找到平面的原因。

> 发现是ba.hpp 的615行 remove_outlier函数中 ` double threshold = residuals[std::floor((1-ratio)*voxhess.plvec_voxels.size())-1];` residuals会变成residuals[-1]导致段错误，系统崩溃。请问有什么解决方法吗

**Comment by lilrookie76** [comment]
> @seanXMU @gongjun136 @zezeuser 如果是这个原因，说明整个场景没有检测到平面，`plvec_voxels.size()=0`。我的建议是voxel_size、eigen_ratio都调大一点（如果现在很小的话），如果是使用默认参数还有这个问题。可以把点云截图放上来看看，让我判断一下hba无法找到平面的原因。
> 
> > 发现是ba.hpp 的615行 remove_outlier函数中 ` double threshold = residuals[std::floor((1-ratio)*voxhess.plvec_voxels.size())-1];` residuals会变成residuals[-1]导致段错误，系统崩溃。请问有什么解决方法吗

您好，我也是同样的问题，这是我的场景(r3live dataset),用visualize.launch启动
![2023-12-29 15-28-15 的屏幕截图](https://github.com/hku-mars/HBA/assets/57083481/72d77603-c3fd-4695-9c40-b6712015c88e)
