### ISSUE TITLE
to undistort the points or not

### ISSUE THREAD

**Issue by CharlieV5** [hku-mars/HBA#21]
Hi, I noticed that there is a variable defined as `undis_t`, which is used to record the time taken to remove distortion from the point cloud. However, it is not being used in practice, so `undis_t` is always equal to 0. I would like to ask if it is necessary to remove distortion from the point cloud at each iteration of the BA algorithm. In your algorithm, are the input `pcd` point clouds the original or the ones with distortion removed? I guess they are the ones with distortion removed because the output of each iteration does not change the coordinates of the points in `pcd`, but only updates the pose of each point cloud frame.
In theory, should the original point cloud be input and the pose of each frame be iteratively optimized in the BA algorithm while removing distortion from the point cloud? After all, the pose of the point cloud frame changes after each iteration, and removing distortion actually depends on these poses.

**Comment by samsdolphin** [comment]
Hi @CharlieV5 , you are right, you can just delete this variable. The input `pcd` is already undistorted.

**Comment by CharlieV5** [comment]
> Hi @CharlieV5 , you are right, you can just delete this variable. The input `pcd` is already undistorted.

Thank you! And I want discuss  the second topic, should the BA algorithm regenerate the undistorted point cloud, since the poses will be updated after each iteration and the distortion removal relies on the poses of frames?
