### ISSUE TITLE
非重合平面之间变为重合

### ISSUE THREAD

**Issue by gongjun136** [hku-mars/HBA#22]
作者你好，不好意思又来提问了，我记得BA算法会对体素内的平面进行约束优化，但是我发现部分不是同一个平面的被优化后变为了重合的平面，如下图所示：
![image](https://github.com/hku-mars/HBA/assets/73570451/f5877907-69ee-49e6-b201-a5011e0f10c2)
![image](https://github.com/hku-mars/HBA/assets/73570451/7c75321e-a1c1-430a-96d6-3fce82dcf5a8)
这就导致了其他部分的分层：
![image](https://github.com/hku-mars/HBA/assets/73570451/60231c34-8bcf-44ba-b1de-f74cc40c38b1)
![image](https://github.com/hku-mars/HBA/assets/73570451/80fb6bb9-90d7-4ea0-a375-ef8164feb7bf)

**Comment by gongjun136** [comment]
@samsdolphin 好的，感谢回复，我会去试试更严格的参数，作者的HBA2预计什么时候发布啊，想看一下最新的代码思路

**Comment by samsdolphin** [comment]
@gongjun136，快了，刚刚毕业，目前在写文章～

**Comment by gongjun136** [comment]
> [@gongjun136](https://github.com/gongjun136)，快了，刚刚毕业，目前在写文章～

作者你好，HBA2是否已经发表了？想参考一下优化后的BA效果

**Comment by gongjun136** [comment]
> [@gongjun136](https://github.com/gongjun136)，快了，刚刚毕业，目前在写文章～

@samsdolphin 作者你好，HBA2是否已经发表了？想参考一下优化后的BA效果
