### ISSUE TITLE
POSE.JSON

### ISSUE THREAD

**Issue by edwardes2201** [hku-mars/HBA#25]
HELLO FRIEND, GREAT JOB, I WANT TO TRY IT BUT I HAVE A QUESTION WHERE TO GET OR HOW THE POSE.JSON FILE IS OBTAINED, I CURRENTLY USE THE LIVOX MID360 WITH FASTLIO2. GREETINGS.

**Comment by Dhagash4** [comment]
@samsdolphin Can you specify exact command how to generate the following file with fast lio?

**Comment by 85256638** [comment]
@samsdolphin , it would be great to let us know the command or changes that need to make allow FastLio to generate the pose.
