### ISSUE TITLE
rviz no data

### ISSUE THREAD

**Issue by jkff00** [hku-mars/HBA#3]
I tried the park data and it does listen to some relevant topics, but rviz doesn't show anything (nor any output files at the end), what could be the problem?
![2023-06-12 18-04-31 的屏幕截图](https://github.com/hku-mars/HBA/assets/94893280/f82d6c2a-f48a-4f6b-84f7-11d5f40db43b)
![2023-06-12 18-08-01 的屏幕截图](https://github.com/hku-mars/HBA/assets/94893280/10ebe76d-9c05-4805-9c63-6f0e168acedf)

**Comment by samsdolphin** [comment]
Hello, I forget to mention, the `hba.launch` only optimizes the poses but does not visualize the point cloud. You could view the point cloud using `visualize.launch`. Hope this helps.

**Comment by jkff00** [comment]
yep,i try and it's work.


WINNER&nbsp;东区
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hku-mars/HBA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月12日(星期一) 晚上7:06
***@***.***&gt;;
抄送:&nbsp;"WINNER ***@***.******@***.***&gt;;
主题:&nbsp;Re: [hku-mars/HBA] rviz no data (Issue #3)





 
Hello, I forget to mention, the hba.launch only optimizes the poses but does not visualize the point cloud. You could view the point cloud using visualize.launch. Hope this helps.

**Comment by Fury-k5** [comment]
I have the same problem as you, but after I launch visualize.launch, the rviz interface still doesn't show anything, do you know what's the reason for this?
