### ISSUE TITLE
the link of example data is invalid

### ISSUE THREAD

**Issue by CharlieV5** [hku-mars/HBA#31]
Hi! Could you please re-upload your example data? The onedrive link cannot be opened now. Thank you!

**Comment by samsdolphin** [comment]
@CharlieV5 Hi, sorry about this. 

Recently, the OneDrive storage plan was changed for our university, so I moved the dataset to Google Drive. 

I have updated the links on GitHub just now. Please check if you can download the demo data with the updated links.

**Comment by CharlieV5** [comment]
Available now! Thank you!
