### ISSUE TITLE
multi session map fusion

### ISSUE THREAD

**Issue by wolf943134497** [hku-mars/HBA#32]
hi @samsdolphin   Thanks for your great work!

If I have two path and map of LIO which have overlapping area，I want to optimize map consistency in overlapping areas and merge wo maps into one consistent map.

Can HBA solve this problem. Thanks

**Comment by samsdolphin** [comment]
Hi @wolf943134497, thanks for using our work. Yes, we do have such support in our coming work, HBA2, which will be released this year.

**Comment by wolf943134497** [comment]
> Hi @wolf943134497, thanks for using our work. Yes, we do have such support in our coming work, HBA2, which will be released this year.

Thanks for your quick reply and released codes, looking forward to HBA2. Thanks
