### ISSUE TITLE
个别私有变量的意义

### ISSUE THREAD

**Issue by Vincent-ping** [hku-mars/HBA#4]
作者你好，感谢开源代码，在阅读代码中有几个问题请教一下，在LAYER类中，有一些私有变量如：part_length， tail ， left_gap_num以及thread_num的计算结果不是很清楚表达的是什么意义，以及如果计算的，望解答，多谢

**Comment by samsdolphin** [comment]
谢谢您关注我们的工作，关于您的提问，这个我得回忆一下0.0
