### ISSUE TITLE
I think the code and the contents of the paper are different.

### ISSUE THREAD

**Issue by jaeseok4104** [hku-mars/HBA#5]
The code has a constraint between all the nodes in the window, and didn't make the constraint of the floor 2 layer.

Can you explain this?

![image](https://github.com/hku-mars/HBA/assets/51950819/e13983e7-821a-4d8c-9b96-faeb9eab2256)

![image](https://github.com/hku-mars/HBA/assets/51950819/cf1f76c5-0b8e-4466-95b1-a64a2812ae6e)

**Comment by samsdolphin** [comment]
Hi @jaeseok4104, yes you are right. In short, we found this implementation has a faster convergence rate and a better precision. We thus open source this version of code instead of the very original one (paper version). However, you could modify the code structure by yourself. Hope this helps.

**Comment by jaeseok4104** [comment]
thanks :) Have you plan to open about paper version code?

**Comment by samsdolphin** [comment]
Haha, this shouldn't be hard for you ;)

**Comment by HaisenbergPeng** [comment]
Hi, after the sliding window ba in the 1st layer， the optimized poses are not used for factor graph, instead, you used the initial poses and the ba hessians. Could you please explain the reason? thanks a lot!
![image](https://github.com/hku-mars/HBA/assets/72208396/bf3ddeb2-6edd-4a38-82f4-f6aeb5030633)

![image](https://github.com/hku-mars/HBA/assets/72208396/681ebf24-5a06-4312-8335-6deedcfa40b3)

**Comment by samsdolphin** [comment]
Hi @HaisenbergPeng, in each local ba, we want the hessians to constrain the relative poses between the 1st layer poses. The optimized poses in each local ba are used to construct the next layer's keyframe.

**Comment by HaisenbergPeng** [comment]
okay, got it! Maybe I could try using the optimized poses of the bottom layer as factors.
