### ISSUE TITLE
Large RAM issue

### ISSUE THREAD

**Issue by wwtinwhu** [hku-mars/HBA#6]
Hello, @samsdolphin . Great work! 

I tested with data (Mid-70) of about 6k frames with 3, 4, 5 layer respectively. However, even with 5 layer setting, the RAM is exceed the max about 16GB. However, from your paper, the RAM cost is smaller than 5GB with 6k frames. What is the reason for this? 

![image](https://github.com/hku-mars/HBA/assets/28035224/1938658c-e13c-4cb1-a21e-8b04278eb085)

**Comment by samsdolphin** [comment]
For your scenario, I would recommend using 32GiB or even 64 GiB RAM computer, which can save the total computation time. In our early development stage, we calculate each layer separately, and we need to save and read each layer's pcds again and again. The local BA, global BA and pose graph optimization functions are performed in different `launch` files. I thought it might be better to combine them together. Hope this helps.

**Comment by wwtinwhu** [comment]
Thanks again for @samsdolphin. The issue here is caused by putting pose.json in the pcd directory. After correcting this, the RAM used is around 4GB with my test data.

**Comment by seajayshore** [comment]
That's good. Thanks for confirming. 

Do the results look "good"? Does the HBA optimisation work well with your Mid-70 data?

**Comment by wwtinwhu** [comment]
@samsdolphin Maybe add a check for opening pose file in read_pose function :)

**Comment by wwtinwhu** [comment]
@seajayshore Hello! I am testing it now! What's your testing scene? Maybe we can communicate with email, and you can find my email in my profile.
