### ISSUE TITLE
std::bad_alloc while launch hba.launch with kitty07

### ISSUE THREAD

**Issue by JACKLiuDay** [hku-mars/HBA#7]
![image](https://github.com/hku-mars/HBA/assets/30967867/3cf5d98c-af5a-44e2-b7bb-9e0e8836d90c)
Hi, thank you for your great work about HBA. I read the paper and try to launch the hba project with kitty07 dataset. But when I launch the file, something wrong happened.

**Comment by JACKLiuDay** [comment]
Hi，I found the reason. It looks like my notebook memory is full. When I run the launch file, memory reach 16G soon. Then report std::bad_alloc

**Comment by samsdolphin** [comment]
Hi @JACKLiuDay, yes, this is an issue, as mentioned in #6. It should be able to work under 32GiB RAM.

**Comment by JACKLiuDay** [comment]
> Hi @JACKLiuDay, yes, this is an issue, as mentioned in #6. It should be able to work under 32GiB RAM.

Hi，thank you for your quick reply. 16G×2 memory module has been ordered on jingdong. I will try HBA again.

**Comment by JACKLiuDay** [comment]
@samsdolphin Hi, I just tried my notebook with 16G×2, and it still shows std::bad_alloc. My notebook now has 27.6G  memory. Maybe I need to buy more RAM?

**Comment by samsdolphin** [comment]
Hi @JACKLiuDay, this is weird. I am testing it on my own laptop (see configuration below), and it works fine for me (with maximum 18G RAM consumption). Can you make sure you are using c++17 (in `CMakeLists.txt`)? Previously I used c++14/c++11, and it failed like this.
![Screenshot from 2023-06-23 19-30-26](https://github.com/hku-mars/HBA/assets/12109266/e9cf439e-3025-40b1-abb9-279e6a8e16f9)

![Screenshot from 2023-06-23 19-27-44](https://github.com/hku-mars/HBA/assets/12109266/f57ce1cd-602c-4d0b-8855-7fa2c9044b24)

**Comment by samsdolphin** [comment]
Hi @JACKLiuDay, can you check [this reply](https://github.com/hku-mars/HBA/issues/6#issuecomment-1604188647) as mentioned in issue #6? This error is similar to yours.

**Comment by JACKLiuDay** [comment]
> Hi @JACKLiuDay, can you check [this reply](https://github.com/hku-mars/HBA/issues/6#issuecomment-1604188647) as mentioned in issue #6? This error is similar to yours.

Hi, I tried the reply in #6. It's not working for me. My pose file was put in the right path and I checked it. 
The cmake was set c++17 and it did not work. My laptop  RAM is the same as yours. I have 27.6G RAM now. But when I launch kitti07, htop shows the RAM surging to 27G fast. Mabybe my CPU not working for this project? My CPU is AMD 5800H.

**Comment by samsdolphin** [comment]
> > Hi @JACKLiuDay, can you check [this reply](https://github.com/hku-mars/HBA/issues/6#issuecomment-1604188647) as mentioned in issue #6? This error is similar to yours.
> 
> Hi, I tried the reply in #6. It's not working for me. My pose file was put in the right path and I checked it. The cmake was set c++17 and it did not work. My laptop RAM is the same as yours. I have 27.6G RAM now. But when I launch kitti07, htop shows the RAM surging to 27G fast. Mabybe my CPU not working for this project? My CPU is AMD 5800H.

Ok, @JACKLiuDay, this is something I haven't been concerned about. You could try it on an Intel laptop. 0.0

**Comment by wwtinwhu** [comment]
It is strange that the terminal has no output. @samsdolphin @JACKLiuDay You can add some print function in the construction of hba before the `printf(''HBA init done'') ` to see which part cause that issue. May help. 

![image](https://github.com/hku-mars/HBA/assets/28035224/d22f7f3c-ddcf-4a53-bc72-04c87457c783)

**Comment by JACKLiuDay** [comment]
> It is strange that the terminal has no output. @samsdolphin @JACKLiuDay You can add some print function in the construction of hba before the `printf(''HBA init done'') ` to see which part cause that issue. May help.
> 
> ![image](https://user-images.githubusercontent.com/28035224/248519765-d22f7f3c-ddcf-4a53-bc72-04c87457c783.png)

Hi, thank you for your advice. I will try it.

**Comment by JACKLiuDay** [comment]
@samsdolphin @wwtinwhu Hi, I found the reason. But some new problem happeded. The function inf mypcl::readpose,   while(!file.eof()) became infinite loop. I changed the function. The HBA init successed. But the pcd load error happened. Some pcd file can not load. 
  std::vector<pose> read_pose(std::string filename,
                              Eigen::Quaterniond qe = Eigen::Quaterniond(1, 0, 0, 0),
                              Eigen::Vector3d te = Eigen::Vector3d(0, 0, 0))
  {
    std::vector<pose> pose_vec;
    std::fstream file;
    file.open(filename);
    double tx, ty, tz, w, x, y, z;
    while(!file.eof())
    {
      file >> tx >> ty >> tz >> w >> x >> y >> z;
      Eigen::Quaterniond q(w, x, y, z);
      Eigen::Vector3d t(tx, ty, tz);
      pose_vec.push_back(pose(qe * q, qe * t + te));
    }
    file.close();
    return pose_vec;
  }

**Comment by samsdolphin** [comment]
> @samsdolphin @wwtinwhu Hi, I found the reason. But some new problem happeded. The function in mypcl::readpose, while(!file.eof()) became infinite loop on my computer. I changed the function. The HBA init successed. But the pcd load error happened. Some pcd file can not load. ![image](https://user-images.githubusercontent.com/30967867/248543817-abb6d48b-d7bd-4f09-b8c0-91818753fab2.png)

Hi @JACKLiuDay, thanks for your feedback and @wwtinwhu's suggestion. I guess the AMD processor caused these issues 0.0

**Comment by JACKLiuDay** [comment]
> > @samsdolphin @wwtinwhu Hi, I found the reason. But some new problem happeded. The function in mypcl::readpose, while(!file.eof()) became infinite loop on my computer. I changed the function. The HBA init successed. But the pcd load error happened. Some pcd file can not load. ![image](https://user-images.githubusercontent.com/30967867/248543817-abb6d48b-d7bd-4f09-b8c0-91818753fab2.png)
> 
> Hi @JACKLiuDay, thanks for your feedback and @wwtinwhu's suggestion. I guess the AMD processor caused these issues 0.0 since I only tested on the Intel computer.

Hi, I found the reason finally. My data path is wrong. It nothing to do with CPU. HBA can run on my notebook successfully. And the result is good for the pointcloud. 
Excellent work!

**Comment by wwtinwhu** [comment]
@JACKLiuDay 解决就好！

**Comment by Gaaaavin** [comment]
@JACKLiuDay Hi, I have the same problem you met. I checked the file path and it is correct. I'm using the provided kitti07 dataset. Do you have any idea on how to debug?
