### ISSUE TITLE
There are only two layers in factor graph

### ISSUE THREAD

**Issue by jkff00** [hku-mars/HBA#8]
hello!
          The number of pose graph optimization layers seems to be only the top and bottom layers, and the middle layer does not add factor maps to participate in optimization(upper_pose && init_pose in pose_graph_optimization()).And I reproduced the park data in the paper, the ground did improve, but as indicated by the white box, some areas have degraded, can you explain? Thank!

![ques](https://github.com/hku-mars/HBA/assets/94893280/b6d75391-b139-433a-94ea-8b0088c569a9)

**Comment by samsdolphin** [comment]
Hi @jkff00 , for your first question, I refer you to #5. For the second question, the area you emphasized is a building surface, which indeed should not be converged. Please see the images below. 
![Screenshot from 2023-06-20 23-15-53](https://github.com/hku-mars/HBA/assets/12109266/bdb8bbde-d871-44ca-8d28-21e745c3540c)
![Screenshot from 2023-06-20 23-17-59](https://github.com/hku-mars/HBA/assets/12109266/29cf16f9-07c3-4380-bf4e-441d2a5a2c66)

**Comment by jkff00** [comment]
Thank you for your reply. I understand.



---Original---
From: "Xiyuan ***@***.***&gt;
Date: Tue, Jun 20, 2023 23:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hku-mars/HBA] There are only two layers in factor graph (Issue#8)




 
Hi @jkff00 , for your first question, I refer you to #5. For the second question, the area you emphasized is a building surface, which indeed should not be converged. Please see the images below.
